exp_name: default_experiment_new
project_name: default_config
checkpoint_dir: ./runs
comment: Experiment comment goes here
data:
  images_dir: "/mnt/space/space-home/wild-me/PIE/bottlenose-dolphin/data/flukebook-384"
  viewpoint_list: ['left', 'right']
  name_keys: ['name']
  crop_bbox: false
  image_size:
    - 384
    - 384
  train:
    anno_path: "/mnt/space/space-home/wild-me/PIE/bottlenose-dolphin/data/flukebook-coco/instances_train2021.json"
    n_filter_min: 4
    n_subsample_max: null
  val:
    anno_path: "/mnt/space/space-home/wild-me/PIE/bottlenose-dolphin/data/flukebook-coco/instances_val2021.json"
    n_filter_min: 2
    n_subsample_max: 10
  test:
    anno_path: "/mnt/space/space-home/wild-me/PIE/bottlenose-dolphin/data/flukebook-coco/instances_val2021.json"
    n_filter_min: 2
    n_subsample_max: 10
    checkpoint_path:  "/mnt/space/space-home/wild-me/wbia-plugin-miew-id/wbia_miew_id/runs/bottlenose-dolphin/l2r_1/efficientnetv2_rw_m-384-arcface/model_best.bin"

engine:
  num_workers: 0
  train_batch_size: 6
  valid_batch_size: 12
  epochs: 30
  seed: 42
  device: cuda
  loss_module: arcface
  use_wandb: false

scheduler_params:
  lr_start: 1.e-5
  lr_max: 1.e-3
  lr_min: 9.e-6
  lr_ramp_ep: 15
  lr_sus_ep: 0
  lr_decay: 0.8
model_params:
  model_name: efficientnetv2_rw_m
  use_fc: false
  fc_dim: 2048
  dropout: 0.0
  loss_module: arcface
  s: 30.0
  margin: 0.50
  ls_eps: 0.0
  theta_zero: 0.785
  pretrained: true
  n_classes: 865 # used for loading checkpoint
test:
  fliplr: false
  fliplr_view: []
  batch_size: 8s